/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AKM.finder;

import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author hp1
 */

public class M8 extends javax.swing.JFrame {
    
 int quauntity = 0;
 int price  = 0;
 float totalprice = 0;
//java.util.Random r=new java.util.Random();
//     int start=1000;
//     int end=10000;
//     int result=r.nextInt(end-start) +start;
 

         

  

    /**
     * Creates new form M8
     */
    public M8() {
        initComponents();
        String contain="12345678910ACGFVBHNMKLOPIJUYH";
        Random rnd=new Random();
        StringBuilder sb= new StringBuilder(4);
         for(int i =0; i<4; i++ )
                {
                 sb.append(contain.charAt(rnd.nextInt(contain.length())));
                }
                String random=sb.toString();
                  jTextField8.setEditable(false);
                  jTextField8.setText(random);
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 12, 12), 10, true));

        jLabel1.setFont(new java.awt.Font("Californian FB", 3, 36)); // NOI18N
        jLabel1.setText("ORDER NOW");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel2.setText("PROUCT KEY");

        jButton1.setBackground(new java.awt.Color(0, 255, 204));
        jButton1.setFont(new java.awt.Font("Cambria Math", 3, 24)); // NOI18N
        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel3.setText("PRODUCT NAME");

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel4.setText("PRODUCT_ID");

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel5.setText("QUANTITY");

        jLabel6.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel6.setText("PRICE");

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel7.setText("SUPPLIER_ID");

        jLabel8.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel8.setText("COURIER_ID");

        jLabel9.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel9.setText("ORDER_ID");

        jLabel10.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel10.setText("DELIVERY_STATUS");

        jLabel11.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        jLabel11.setText("PHONE NUMBER");

        jButton4.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton4.setText("CONFIRM");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jButton5.setText("PLACE ORDER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(107, 107, 107)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(70, 70, 70)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField6)
                                .addComponent(jTextField7)
                                .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(159, 159, 159)
                            .addComponent(jButton4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton5)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField5)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jTextField12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        quauntity++;
            //  plus
            String p =  String.valueOf(quauntity);
            jTextField4.setText(p);
            totalprice = price+totalprice;
            jTextField5.setText(totalprice+" ");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int id=Integer.parseInt(jTextField1.getText());
       
        if(id==4441)
        {
           jTextField2.setText("INTEXCLOUD3G"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123401");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=5000;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH14");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365GHJ");
           }
        else if(id==4442)
        {
            jTextField2.setText("IPHONE11PRO"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB1234VB");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=1500000;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH15");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365G01");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("2DAYS");
           jTextField9.setEditable(false);
        }
          else if(id==4443)
        {
            jTextField2.setText("IPHONEX"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123403");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=90000;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH14");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365G02");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("6DAYS");
           jTextField9.setEditable(false);
        }
        else if(id==4444)
        {
           jTextField2.setText("samsung m31"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123402");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=16999;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH15");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365G03");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("7DAYS");
           jTextField9.setEditable(false);
        }
        else if(id==4445)
        {
           jTextField2.setText("NORMAL WATCH"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123409");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=99;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH18");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365G04");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("10DAYS");
           jTextField9.setEditable(false);
        }
        else if(id==4446)
        {
           jTextField2.setText("JORDANA1"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123408");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=1399999;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH19");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365G04");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("3DAYS");
           jTextField9.setEditable(false);
        }
        else if(id==4447)
        {
           jTextField2.setText("20KGDUMBLES"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123406");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=1500;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH17");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365G03");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("8DAYS");
           jTextField9.setEditable(false);
        }
        else if(id==4448)
        {
           jTextField2.setText("PEANUT BUTTER"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123404");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=150;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH18");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365G02");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("6DAYS");
           jTextField9.setEditable(false);
        }
         else if(id==4449)
        {
           jTextField2.setText("REALMEBUDS"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123405");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=1500;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH15");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365G01");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("9DAYS");
           jTextField9.setEditable(false);
        }
            else if(id==4450)
        {
           jTextField2.setText("SPEAKERS"); 
           jTextField2.setEditable(false);
           jTextField3.setText("SD56789MNB123407");
           jTextField3.setEditable(false);
           jTextField4.setText("1");
           price=1399;
           jTextField5.setText(" "+price);
           jTextField5.setEditable(false);
           jTextField6.setText("A34D60KH14");
           jTextField6.setEditable(false);
           jTextField7.setText("QWED12365GHJ");
           jTextField7.setEditable(false);
         
           jTextField8.setEditable(false);
           jTextField9.setText("5DAYS");
           jTextField9.setEditable(false);
        }
       else{
                JOptionPane.showMessageDialog(null, "PLEASE ENTER CORRECT PRODUCT KEY");
                jTextField1.setText(" ");
                jTextField2.setText(" ");
                jTextField3.setText(" ");
                jTextField4.setText(" ");
                jTextField5.setText(" ");
                jTextField6.setText(" ");
                jTextField7.setText(" ");
                jTextField8.setText(" ");
                jTextField9.setText(" ");
                jTextField10.setText(" ");
                jTextField11.setText(" ");
                jTextField12.setText(" ");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       
        quauntity--;
            //  plus
            if(quauntity>=0){
                String p =  String.valueOf(quauntity);
            jTextField4.setText(p);
            totalprice = totalprice-price;
            jTextField5.setText(totalprice+" ");
            
            }
            else{
                quauntity = 0;
                jTextField4.setText("0");
                jTextField5.setText("0");
                 }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Long ph=Long.parseUnsignedLong(jTextField10.getText());
        java.sql.Connection con=null;
        PreparedStatement pstmt=null;
        ResultSet rs=null;
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","keshav15");
            pstmt=con.prepareStatement("select * from customer where PHONE_NUMBER=?");
            pstmt.setLong(1,ph);
            rs=pstmt.executeQuery();
            while(rs.next())
            {
                if(ph.equals(rs.getLong("PHONE_NUMBER")))
                {
                    JOptionPane.showMessageDialog(null, "YOUR PHONE NUMBER IS CORRECT");
                    jTextField10.setEditable(false); 
                    java.util.Date utilDate = new java.util.Date();
                     java.sql.Timestamp sqlTS = new java.sql.Timestamp(utilDate.getTime());
                     jTextField12.setText(" "+sqlTS);
                     jTextField11.setText(" "+utilDate);
                     jTextField11.setEditable(false);
                     jTextField12.setEditable(false);
                 }
                else
                {
                    JOptionPane.showMessageDialog(null, "PLEASE ENTER CORRECT NUMBER");
                }
            }
          }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try
        {
            
               Class.forName("oracle.jdbc.driver.OracleDriver");
              try (java.sql.Connection con = DriverManager.getConnection( "jdbc:oracle:thin:@localhost:1521:xe","system","keshav15")) {
                String qu="INSERT INTO cart1 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmt=con.prepareStatement(qu);
                pstmt.setString(1,jTextField8.getText());
                pstmt.setString(2,jTextField9.getText());
                pstmt.setString(3, jTextField11.getText());
                pstmt.setString(4,jTextField12.getText());
                pstmt.setInt(5,Integer.parseInt(jTextField4.getText()));
                Long ph=Long.parseUnsignedLong(jTextField10.getText());
                pstmt.setLong(6,ph);
                
                pstmt.setString(7,jTextField3.getText());
                pstmt.setString(8,jTextField6.getText());
                 pstmt.setString(9,jTextField7.getText());
                  pstmt.setFloat(10,Float.parseFloat(jTextField5.getText()));
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"ORDER IS SUCCESSFULLY PLACED");
              
                new M9().setVisible(true);
            }
              
             
         }
         catch(HeadlessException | ClassNotFoundException | SQLException e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
